name: Setup and build
description: A composite action to setup and build the web app

inputs:
  host:
    description: "Host"
    required: true
  username:
    description: "Username"
    required: true
  password:
    description: "Password"
    required: true
  ssh-private-key:
    description: "SSH private key"
    required: true
  database:
    description: "Database"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
        chmod 600 ~/.ssh/deploy.key
        cat >>~/.ssh/config <<END
        Host deploy
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        END
      env:
        SSH_HOST: ${{ inputs.host }}
        SSH_USER: ${{ inputs.username }}
        SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}

    - name: Export database
      shell: bash
      run: LANG="en_US.UTF-8" ; ssh -T -p 5022 deploy "mysqldump -P 3306 -u $USERNAME -p$PASSWORD $DATABASE > github_actions.sql"
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        DATABASE: ${{ inputs.database }}

    - name: Import database
      shell: bash
      run: |
        mkdir -p ~/database
        LANG="en_US.UTF-8" ; scp -i ~/.ssh/deploy.key -P 5022 $USERNAME@$SERVER:~/github_actions.sql ~/database
      env:
        SERVER: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}

    - name: Checkout database
      shell: bash
      run: mysql -h 127.0.0.1 -u $USERNAME -p$PASSWORD $DATABASE < ~/database/github_actions.sql
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        DATABASE: ${{ inputs.database }}

    - name: Setup node
      uses: actions/setup-node@v4.0.2
      with:
        node-version-file: ".nvmrc"

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Create .env file
      shell: bash
      run: |
        echo "MYSQL_HOST=127.0.0.1" >> .env
        echo "MYSQL_USER=$USERNAME" >> .env
        echo "MYSQL_PASSWORD=$PASSWORD" >> .env
        echo "MYSQL_DATABASE=$DATABASE" >> .env
        echo "MYSQL_PORT=3306" >> .env
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        DATABASE: ${{ inputs.database }}

    - name: Build web app
      shell: bash
      run: npm run build
