name: Setup test database
description: Export the remote database and import it into the local CI MariaDB service

inputs:
  host:
    description: "Host"
    required: true
  username:
    description: "Username"
    required: true
  password:
    description: "Password"
    required: true
  ssh-private-key:
    description: "SSH private key"
    required: true
  database:
    description: "Database"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
        chmod 600 ~/.ssh/deploy.key
        cat >>~/.ssh/config <<END
        Host deploy
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deploy.key
          StrictHostKeyChecking no
        END
      env:
        SSH_HOST: ${{ inputs.host }}
        SSH_USER: ${{ inputs.username }}
        SSH_PRIVATE_KEY: ${{ inputs.ssh-private-key }}

    - name: Export database
      shell: bash
      run: LANG="en_US.UTF-8" ; ssh -T -p 5022 deploy "export MYSQL_PWD=$PASSWORD; mysqldump -P 3306 -u $USERNAME $DATABASE > github_actions.sql"
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        DATABASE: ${{ inputs.database }}

    - name: Import database
      shell: bash
      run: |
        mkdir -p ~/database
        LANG="en_US.UTF-8" ; scp -P 5022 deploy:~/github_actions.sql ~/database
      env:
        SERVER: ${{ inputs.host }}
        USERNAME: ${{ inputs.username }}

    - name: Checkout database
      shell: bash
      run: mysql -h 127.0.0.1 -u $USERNAME $DATABASE < ~/database/github_actions.sql
      env:
        USERNAME: ${{ inputs.username }}
        MYSQL_PWD: ${{ inputs.password }}
        DATABASE: ${{ inputs.database }}
