name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks-and-run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      HUSKY: 0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.2

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Prettier
        run: npm run prettier

      - name: Run test
        run: npm run test

  deployment:
    runs-on: ubuntu-latest
    needs: checks-and-run-tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: nztunnellers.com_nextjstest/
          exclude: |
            .git/**
            .github/**
            .husky/**
            __tests__/**
            docs/**
            .gitignore
            README.md
            jest.config.js
            jest.setup.js
            playwright.config.js

      - name: Build and restart web app
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -l accordon -p 5022 world-375.fr.planethoster.net
          sleep 2
          source nodevenv/nztunnellers.com_nextjstest/19/bin/activate
          cd nztunnellers.com_nextjstest
          npm run build
