name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  checks-and-run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      HUSKY: 0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.2

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Prettier
        run: npm run prettier

      - name: Run test
        run: npm run test

  deployment:
    runs-on: ubuntu-latest
    needs: checks-and-run-tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.FTP_SERVER }}
          SSH_USER: ${{ secrets.FTP_USERNAME }}

      - name: Export database
        run: |
          ssh deploy -l ${{ secrets.FTP_USERNAME}} -p 5022 ${{ secrets.FTP_SERVER }}

        #   mysqldump -u ${{ secrets.FTP_USERNAME}} -p${{ secrets.FTP_PASSWORD }} ${{ secrets.MYSQL_DATABASE }} > /nztunnellers.com_database/github_actions.sql

      # - name: Import database
      #   run: |
      #     scp -i deploy -P 5022 ${{ secrets.FTP_USERNAME}}@${{ secrets.FTP_SERVER }}:~/nztunnellers.com_database/github_actions.sql ~/database/
      #     cd ~/database
      #     ls

      # - name: Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     server-dir: nztunnellers.com_nextjstest/
      #     exclude: |
      #       .git/**
      #       .github/**
      #       .husky/**
      #       __tests__/**
      #       docs/**
      #       .gitignore
      #       README.md
      #       jest.config.js
      #       jest.setup.js
      #       playwright.config.js

      # - name: Build web app
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     port: 5022
      #     script: |
      #       source nodevenv/nztunnellers.com_nextjstest/19/bin/activate
      #       cd nztunnellers.com_nextjstest
      #       npm install --include=dev
      #       npm run build
