name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.2

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Prettier
        run: npm run prettier

      - name: Build web app
        run: npm run build

      - name: Run test
        run: npm run test

  run-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build-and-run-tests
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.2

      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.DEPLOY_USERNAME }}
          SSH_HOST: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END

      - name: Open SSH Tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -N -L 3306:localhost:3306 ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_SERVER }} &

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Start web app
        run: npm run start &
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_PORT: 3306
          VERCEL_ENV: local

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4.3.6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10

  # deployment:
  #   runs-on: ubuntu-latest
  #   needs: run-e2e-tests
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4.1.2

  #     - name: Sync files
  #       uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  #       with:
  #         server: ${{ secrets.DEPLOY_SERVER }}
  #         username: ${{ secrets.DEPLOY_USERNAME }}
  #         password: ${{ secrets.DEPLOY_PASSWORD }}
  #         protocol: ftps
  #         port: 5022
